import type { DeviceSpec } from "@/types";

export const deviceDatabase: Record<string, DeviceSpec> = {
  // Apple iPhones
  "apple_iphone_16_pro_max-13221": {
    id: "apple_iphone_16_pro_max-13221",
    name: "Apple iPhone 16 Pro Max",
    brand: "Apple",
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro-max.jpg",
    specs: {
      display: "6.9\" Super Retina XDR OLED",
      displayTech: "LTPO Super Retina XDR OLED, 120Hz, HDR10",
      refreshRate: "120Hz ProMotion",
      chipset: "Apple A18 Pro (3nm)",
      gpu: "Apple GPU (6-core graphics)",
      ram: "8GB",
      storage: "256GB/512GB/1TB",
      mainCamera: "48MP + 12MP + 12MP",
      frontCamera: "12MP SL 3D",
      battery: "4685 mAh Li-Ion",
      charging: "45W wired, 25W wireless",
      os: "iOS 18",
      year: "September 2024",
      weight: "227g",
      dimensions: "163 x 77.6 x 8.3 mm",
    },
    raw: {},
  },
  "apple_iphone_16_pro-13220": {
    id: "apple_iphone_16_pro-13220",
    name: "Apple iPhone 16 Pro",
    brand: "Apple",
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro.jpg",
    specs: {
      display: "6.3\" Super Retina XDR OLED",
      displayTech: "LTPO Super Retina XDR OLED, 120Hz, HDR10",
      refreshRate: "120Hz ProMotion",
      chipset: "Apple A18 Pro (3nm)",
      gpu: "Apple GPU (6-core graphics)",
      ram: "8GB",
      storage: "128GB/256GB/512GB/1TB",
      mainCamera: "48MP + 12MP + 12MP",
      frontCamera: "12MP SL 3D",
      battery: "3582 mAh Li-Ion",
      charging: "45W wired, 25W wireless",
      os: "iOS 18",
      year: "September 2024",
      weight: "199g",
      dimensions: "149.6 x 71.5 x 8.3 mm",
    },
    raw: {},
  },
  "apple_iphone_16-13222": {
    id: "apple_iphone_16-13222",
    name: "Apple iPhone 16",
    brand: "Apple",
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16.jpg",
    specs: {
      display: "6.1\" Super Retina XDR OLED",
      displayTech: "Super Retina XDR OLED, HDR10",
      refreshRate: "60Hz",
      chipset: "Apple A18 (3nm)",
      gpu: "Apple GPU (5-core graphics)",
      ram: "8GB",
      storage: "128GB/256GB/512GB",
      mainCamera: "48MP + 12MP",
      frontCamera: "12MP SL 3D",
      battery: "3561 mAh Li-Ion",
      charging: "45W wired, 25W wireless",
      os: "iOS 18",
      year: "September 2024",
      weight: "170g",
      dimensions: "147.6 x 71.6 x 7.8 mm",
    },
    raw: {},
  },
  "apple_iphone_16_plus-13223": {
    id: "apple_iphone_16_plus-13223",
    name: "Apple iPhone 16 Plus",
    brand: "Apple",
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-plus.jpg",
    specs: {
      display: "6.7\" Super Retina XDR OLED",
      displayTech: "Super Retina XDR OLED, HDR10",
      refreshRate: "60Hz",
      chipset: "Apple A18 (3nm)",
      gpu: "Apple GPU (5-core graphics)",
      ram: "8GB",
      storage: "128GB/256GB/512GB",
      mainCamera: "48MP + 12MP",
      frontCamera: "12MP SL 3D",
      battery: "4674 mAh Li-Ion",
      charging: "45W wired, 25W wireless",
      os: "iOS 18",
      year: "September 2024",
      weight: "199g",
      dimensions: "160.9 x 77.8 x 7.8 mm",
    },
    raw: {},
  },
  "apple_iphone_15_pro_max-12504": {
    id: "apple_iphone_15_pro_max-12504",
    name: "Apple iPhone 15 Pro Max",
    brand: "Apple",
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro-max.jpg",
    specs: {
      display: "6.7\" Super Retina XDR OLED",
      displayTech: "LTPO Super Retina XDR OLED, 120Hz, HDR10",
      refreshRate: "120Hz ProMotion",
      chipset: "Apple A17 Pro (3nm)",
      gpu: "Apple GPU (6-core graphics)",
      ram: "8GB",
      storage: "256GB/512GB/1TB",
      mainCamera: "48MP + 12MP + 12MP",
      frontCamera: "12MP SL 3D",
      battery: "4441 mAh Li-Ion",
      charging: "27W wired, 15W wireless",
      os: "iOS 17",
      year: "September 2023",
      weight: "221g",
      dimensions: "159.9 x 76.7 x 8.3 mm",
    },
    raw: {},
  },
  "apple_iphone_15_pro-12503": {
    id: "apple_iphone_15_pro-12503",
    name: "Apple iPhone 15 Pro",
    brand: "Apple",
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro.jpg",
    specs: {
      display: "6.1\" Super Retina XDR OLED",
      displayTech: "LTPO Super Retina XDR OLED, 120Hz, HDR10",
      refreshRate: "120Hz ProMotion",
      chipset: "Apple A17 Pro (3nm)",
      gpu: "Apple GPU (6-core graphics)",
      ram: "8GB",
      storage: "128GB/256GB/512GB/1TB",
      mainCamera: "48MP + 12MP + 12MP",
      frontCamera: "12MP SL 3D",
      battery: "3274 mAh Li-Ion",
      charging: "27W wired, 15W wireless",
      os: "iOS 17",
      year: "September 2023",
      weight: "187g",
      dimensions: "146.6 x 70.6 x 8.3 mm",
    },
    raw: {},
  },

  // Samsung Galaxy S Series
  "samsung_galaxy_s25_ultra-13114": {
    id: "samsung_galaxy_s25_ultra-13114",
    name: "Samsung Galaxy S25 Ultra",
    brand: "Samsung",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-ultra.jpg",
    specs: {
      display: "6.8\" Dynamic AMOLED 2X",
      displayTech: "Dynamic AMOLED 2X, 120Hz, HDR10+",
      refreshRate: "120Hz",
      chipset: "Snapdragon 8 Elite (3nm)",
      gpu: "Adreno 830",
      ram: "12GB/16GB",
      storage: "256GB/512GB/1TB",
      mainCamera: "200MP + 50MP + 10MP + 12MP",
      frontCamera: "12MP",
      battery: "5000 mAh Li-Ion",
      charging: "45W wired, 15W wireless",
      os: "Android 15, One UI 7",
      year: "January 2025",
      weight: "218g",
      dimensions: "162.8 x 77.6 x 8.2 mm",
    },
    raw: {},
  },
  "samsung_galaxy_s24_ultra-12832": {
    id: "samsung_galaxy_s24_ultra-12832",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-ultra.jpg",
    specs: {
      display: "6.8\" Dynamic AMOLED 2X",
      displayTech: "Dynamic AMOLED 2X, 120Hz, HDR10+",
      refreshRate: "120Hz",
      chipset: "Snapdragon 8 Gen 3 (4nm)",
      gpu: "Adreno 750",
      ram: "12GB",
      storage: "256GB/512GB/1TB",
      mainCamera: "200MP + 12MP + 50MP + 10MP",
      frontCamera: "12MP",
      battery: "5000 mAh Li-Ion",
      charging: "45W wired, 15W wireless",
      os: "Android 14, One UI 6.1",
      year: "January 2024",
      weight: "232g",
      dimensions: "162.3 x 79 x 8.6 mm",
    },
    raw: {},
  },
  "samsung_galaxy_s24_plus-12833": {
    id: "samsung_galaxy_s24_plus-12833",
    name: "Samsung Galaxy S24+",
    brand: "Samsung",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-plus.jpg",
    specs: {
      display: "6.7\" Dynamic AMOLED 2X",
      displayTech: "Dynamic AMOLED 2X, 120Hz, HDR10+",
      refreshRate: "120Hz",
      chipset: "Snapdragon 8 Gen 3 / Exynos 2400",
      gpu: "Adreno 750 / Xclipse 940",
      ram: "12GB",
      storage: "256GB/512GB",
      mainCamera: "50MP + 12MP + 10MP",
      frontCamera: "12MP",
      battery: "4900 mAh Li-Ion",
      charging: "45W wired, 15W wireless",
      os: "Android 14, One UI 6.1",
      year: "January 2024",
      weight: "196g",
      dimensions: "158.5 x 75.9 x 7.6 mm",
    },
    raw: {},
  },
  "samsung_galaxy_s24-12834": {
    id: "samsung_galaxy_s24-12834",
    name: "Samsung Galaxy S24",
    brand: "Samsung",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24.jpg",
    specs: {
      display: "6.2\" Dynamic AMOLED 2X",
      displayTech: "Dynamic AMOLED 2X, 120Hz, HDR10+",
      refreshRate: "120Hz",
      chipset: "Snapdragon 8 Gen 3 / Exynos 2400",
      gpu: "Adreno 750 / Xclipse 940",
      ram: "8GB",
      storage: "128GB/256GB",
      mainCamera: "50MP + 12MP + 10MP",
      frontCamera: "12MP",
      battery: "4000 mAh Li-Ion",
      charging: "25W wired, 15W wireless",
      os: "Android 14, One UI 6.1",
      year: "January 2024",
      weight: "167g",
      dimensions: "147 x 70.6 x 7.6 mm",
    },
    raw: {},
  },

  // Samsung Galaxy Z Series
  "samsung_galaxy_z_fold6-13041": {
    id: "samsung_galaxy_z_fold6-13041",
    name: "Samsung Galaxy Z Fold6",
    brand: "Samsung",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold6.jpg",
    specs: {
      display: "7.6\" Foldable Dynamic AMOLED 2X",
      displayTech: "Foldable Dynamic AMOLED 2X, 120Hz",
      refreshRate: "120Hz",
      chipset: "Snapdragon 8 Gen 3 (4nm)",
      gpu: "Adreno 750",
      ram: "12GB",
      storage: "256GB/512GB/1TB",
      mainCamera: "50MP + 12MP + 10MP",
      frontCamera: "10MP + 4MP (under display)",
      battery: "4400 mAh Li-Ion",
      charging: "25W wired, 15W wireless",
      os: "Android 14, One UI 6.1.1",
      year: "July 2024",
      weight: "239g",
      dimensions: "Unfolded: 153.5 x 132.6 x 5.6 mm",
    },
    raw: {},
  },
  "samsung_galaxy_z_flip6-13042": {
    id: "samsung_galaxy_z_flip6-13042",
    name: "Samsung Galaxy Z Flip6",
    brand: "Samsung",
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip6.jpg",
    specs: {
      display: "6.7\" Foldable Dynamic AMOLED 2X",
      displayTech: "Foldable Dynamic AMOLED 2X, 120Hz",
      refreshRate: "120Hz",
      chipset: "Snapdragon 8 Gen 3 (4nm)",
      gpu: "Adreno 750",
      ram: "12GB",
      storage: "256GB/512GB",
      mainCamera: "50MP + 12MP",
      frontCamera: "10MP",
      battery: "4000 mAh Li-Ion",
      charging: "25W wired, 15W wireless",
      os: "Android 14, One UI 6.1.1",
      year: "July 2024",
      weight: "187g",
      dimensions: "Unfolded: 165.1 x 71.9 x 6.9 mm",
    },
    raw: {},
  },

  // Google Pixel
  "google_pixel_9_pro_xl-13095": {
    id: "google_pixel_9_pro_xl-13095",
    name: "Google Pixel 9 Pro XL",
    brand: "Google",
    image: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9-pro-xl.jpg",
    specs: {
      display: "6.8\" LTPO OLED",
      displayTech: "LTPO OLED, 120Hz, HDR10+",
      refreshRate: "120Hz",
      chipset: "Google Tensor G4 (4nm)",
      gpu: "Mali-G715 MC10",
      ram: "16GB",
      storage: "128GB/256GB/512GB/1TB",
      mainCamera: "50MP + 48MP + 48MP",
      frontCamera: "42MP",
      battery: "5060 mAh Li-Ion",
      charging: "37W wired, 23W wireless",
      os: "Android 15",
      year: "August 2024",
      weight: "221g",
      dimensions: "162.8 x 76.6 x 8.5 mm",
    },
    raw: {},
  },
  "google_pixel_9_pro-13096": {
    id: "google_pixel_9_pro-13096",
    name: "Google Pixel 9 Pro",
    brand: "Google",
    image: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9-pro.jpg",
    specs: {
      display: "6.3\" LTPO OLED",
      displayTech: "LTPO OLED, 120Hz, HDR10+",
      refreshRate: "120Hz",
      chipset: "Google Tensor G4 (4nm)",
      gpu: "Mali-G715 MC10",
      ram: "16GB",
      storage: "128GB/256GB/512GB/1TB",
      mainCamera: "50MP + 48MP + 48MP",
      frontCamera: "42MP",
      battery: "4700 mAh Li-Ion",
      charging: "37W wired, 23W wireless",
      os: "Android 15",
      year: "August 2024",
      weight: "199g",
      dimensions: "152.8 x 72 x 8.5 mm",
    },
    raw: {},
  },
  "google_pixel_9-13097": {
    id: "google_pixel_9-13097",
    name: "Google Pixel 9",
    brand: "Google",
    image: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9.jpg",
    specs: {
      display: "6.3\" OLED",
      displayTech: "OLED, 120Hz, HDR10+",
      refreshRate: "120Hz",
      chipset: "Google Tensor G4 (4nm)",
      gpu: "Mali-G715 MC10",
      ram: "12GB",
      storage: "128GB/256GB",
      mainCamera: "50MP + 48MP",
      frontCamera: "10.5MP",
      battery: "4700 mAh Li-Ion",
      charging: "27W wired, 15W wireless",
      os: "Android 15",
      year: "August 2024",
      weight: "198g",
      dimensions: "152.8 x 72 x 8.5 mm",
    },
    raw: {},
  },

  // OnePlus
  "oneplus_13-13014": {
    id: "oneplus_13-13014",
    name: "OnePlus 13",
    brand: "OnePlus",
    image: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-13.jpg",
    specs: {
      display: "6.82\" LTPO AMOLED",
      displayTech: "LTPO AMOLED, 120Hz, HDR10+",
      refreshRate: "120Hz",
      chipset: "Snapdragon 8 Elite (3nm)",
      gpu: "Adreno 830",
      ram: "12GB/16GB/24GB",
      storage: "256GB/512GB/1TB",
      mainCamera: "50MP + 50MP + 50MP",
      frontCamera: "32MP",
      battery: "6000 mAh Li-Ion",
      charging: "100W wired, 50W wireless",
      os: "Android 15, OxygenOS 15",
      year: "December 2024",
      weight: "213g",
      dimensions: "162.8 x 76.8 x 8.5 mm",
    },
    raw: {},
  },
  "oneplus_12-12172": {
    id: "oneplus_12-12172",
    name: "OnePlus 12",
    brand: "OnePlus",
    image: "https://fdn2.gsmarena.com/vv/bigpic/oneplus-12.jpg",
    specs: {
      display: "6.82\" LTPO AMOLED",
      displayTech: "LTPO AMOLED, 120Hz, HDR10+",
      refreshRate: "120Hz",
      chipset: "Snapdragon 8 Gen 3 (4nm)",
      gpu: "Adreno 750",
      ram: "12GB/16GB",
      storage: "256GB/512GB",
      mainCamera: "50MP + 64MP + 48MP",
      frontCamera: "32MP",
      battery: "5400 mAh Li-Ion",
      charging: "100W wired, 50W wireless",
      os: "Android 14, OxygenOS 14",
      year: "December 2023",
      weight: "220g",
      dimensions: "164.3 x 75.8 x 9.2 mm",
    },
    raw: {},
  },

  // Xiaomi
  "xiaomi_15_pro-13015": {
    id: "xiaomi_15_pro-13015",
    name: "Xiaomi 15 Pro",
    brand: "Xiaomi",
    image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-15-pro.jpg",
    specs: {
      display: "6.73\" LTPO AMOLED",
      displayTech: "LTPO AMOLED, 120Hz, HDR10+",
      refreshRate: "120Hz",
      chipset: "Snapdragon 8 Elite (3nm)",
      gpu: "Adreno 830",
      ram: "12GB/16GB",
      storage: "256GB/512GB/1TB",
      mainCamera: "50MP + 50MP + 50MP",
      frontCamera: "32MP",
      battery: "6100 mAh Li-Ion",
      charging: "90W wired, 50W wireless",
      os: "Android 15, HyperOS 2",
      year: "October 2024",
      weight: "213g",
      dimensions: "161.2 x 76.3 x 8.4 mm",
    },
    raw: {},
  },
  "xiaomi_14_ultra-12624": {
    id: "xiaomi_14_ultra-12624",
    name: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    image: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14-ultra.jpg",
    specs: {
      display: "6.73\" LTPO AMOLED",
      displayTech: "LTPO AMOLED, 120Hz, HDR10+",
      refreshRate: "120Hz",
      chipset: "Snapdragon 8 Gen 3 (4nm)",
      gpu: "Adreno 750",
      ram: "16GB",
      storage: "256GB/512GB/1TB",
      mainCamera: "50MP + 50MP + 50MP + 50MP",
      frontCamera: "32MP",
      battery: "5000 mAh Li-Ion",
      charging: "90W wired, 80W wireless",
      os: "Android 14, HyperOS",
      year: "February 2024",
      weight: "224g",
      dimensions: "161.4 x 75.3 x 9.2 mm",
    },
    raw: {},
  },

  // Nothing
  "nothing_phone_2a_plus-13108": {
    id: "nothing_phone_2a_plus-13108",
    name: "Nothing Phone 2a Plus",
    brand: "Nothing",
    image: "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a-plus.jpg",
    specs: {
      display: "6.7\" AMOLED",
      displayTech: "Flexible AMOLED, 120Hz, HDR10+",
      refreshRate: "120Hz",
      chipset: "MediaTek Dimensity 7350 Pro (4nm)",
      gpu: "Mali-G610 MC4",
      ram: "8GB/12GB",
      storage: "256GB/512GB",
      mainCamera: "50MP + 50MP",
      frontCamera: "50MP",
      battery: "5000 mAh Li-Ion",
      charging: "50W wired",
      os: "Android 14, Nothing OS 2.6",
      year: "August 2024",
      weight: "197g",
      dimensions: "161.7 x 76.3 x 8.6 mm",
    },
    raw: {},
  },
  "nothing_phone_2-12701": {
    id: "nothing_phone_2-12701",
    name: "Nothing Phone 2",
    brand: "Nothing",
    image: "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2.jpg",
    specs: {
      display: "6.7\" LTPO OLED",
      displayTech: "LTPO OLED, 120Hz, HDR10+",
      refreshRate: "120Hz",
      chipset: "Snapdragon 8+ Gen 1 (4nm)",
      gpu: "Adreno 730",
      ram: "8GB/12GB",
      storage: "128GB/256GB/512GB",
      mainCamera: "50MP + 50MP",
      frontCamera: "32MP",
      battery: "4700 mAh Li-Ion",
      charging: "45W wired",
      os: "Android 13, Nothing OS 2.0",
      year: "July 2023",
      weight: "201g",
      dimensions: "162.1 x 76.4 x 8.6 mm",
    },
    raw: {},
  },

  // Motorola
  "motorola_edge_50_ultra-12943": {
    id: "motorola_edge_50_ultra-12943",
    name: "Motorola Edge 50 Ultra",
    brand: "Motorola",
    image: "https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-ultra.jpg",
    specs: {
      display: "6.7\" P-OLED",
      displayTech: "P-OLED, 144Hz, HDR10+",
      refreshRate: "144Hz",
      chipset: "Snapdragon 8s Gen 3 (4nm)",
      gpu: "Adreno 735",
      ram: "16GB",
      storage: "512GB/1TB",
      mainCamera: "50MP + 64MP + 50MP",
      frontCamera: "50MP",
      battery: "4500 mAh Li-Ion",
      charging: "125W wired, 50W wireless",
      os: "Android 14, Hello UI",
      year: "April 2024",
      weight: "197g",
      dimensions: "161.1 x 72.4 x 8.6 mm",
    },
    raw: {},
  },

  // Sony
  "sony_xperia_1_vi-12945": {
    id: "sony_xperia_1_vi-12945",
    name: "Sony Xperia 1 VI",
    brand: "Sony",
    image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-vi.jpg",
    specs: {
      display: "6.5\" LTPO OLED",
      displayTech: "LTPO OLED, 120Hz, HDR10",
      refreshRate: "120Hz",
      chipset: "Snapdragon 8 Gen 3 (4nm)",
      gpu: "Adreno 750",
      ram: "12GB",
      storage: "256GB/512GB",
      mainCamera: "52MP + 12MP + 12MP",
      frontCamera: "12MP",
      battery: "5000 mAh Li-Ion",
      charging: "30W wired",
      os: "Android 14",
      year: "May 2024",
      weight: "192g",
      dimensions: "165 x 74 x 8.3 mm",
    },
    raw: {},
  },
};

export function getDeviceById(id: string): DeviceSpec | null {
  return deviceDatabase[id] || null;
}

export function searchDevices(query: string): DeviceSpec[] {
  const normalizedQuery = query.toLowerCase();
  return Object.values(deviceDatabase).filter(device =>
    device.name.toLowerCase().includes(normalizedQuery) ||
    device.brand.toLowerCase().includes(normalizedQuery)
  );
}

export function getAllDevices(): DeviceSpec[] {
  return Object.values(deviceDatabase);
}
